# Generated by Django 4.2.3 on 2023-10-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_description', models.CharField(default='gross per month', max_length=50)),
                ('salary_currency', models.CharField(default='PLN', max_length=10)),
                ('job_responsibilities', models.TextField()),
                ('job_requirements', models.TextField()),
                ('job_published_at', models.DateTimeField(auto_now_add=True)),
                ('job_application_deadline', models.DateTimeField()),
                ('recruitment_type', models.CharField(blank=True, max_length=100)),
                ('application_process', models.TextField()),
                ('job_benefits', models.TextField()),
                ('job_additional_information', models.TextField()),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfileMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
