# Generated by Django 4.2.3 on 2023-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary_currency',
            field=models.CharField(default='PLN', max_length=5),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_description',
            field=models.CharField(default='per hour', max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
