# Generated by Django 4.2.3 on 2023-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_joboffer_salary_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_description',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_type',
            field=models.CharField(default='per hour', max_length=20),
        ),
    ]
