# Generated by Django 4.2.3 on 2023-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_rename_jobofferskills_jobofferskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobofferskill',
            name='skill_type',
            field=models.CharField(choices=[('required', 'Required'), ('optional', 'Optional')], default='required', max_length=40),
        ),
    ]
