# Generated by Django 4.2.3 on 2023-11-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_jobofferskill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferskill',
            name='skill_type',
            field=models.CharField(choices=[('required', 'Required'), ('optional', 'Optional')], max_length=40),
        ),
    ]
