# Generated by Django 4.2.3 on 2023-11-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_alter_jobofferskill_skill_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='job_type',
            new_name='work_schedule',
        ),
    ]
