# Generated by Django 4.2.3 on 2023-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_rename_job_type_joboffer_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(default='b2b', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='position_level',
            field=models.CharField(default='junior', max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='work_schedule',
            field=models.CharField(max_length=100),
        ),
    ]
