# Generated by Django 4.2.3 on 2023-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0009_alter_joboffer_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='specialization',
            field=models.CharField(default='frontend', max_length=100),
        ),
    ]
