# Generated by Django 4.2.3 on 2023-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0010_joboffer_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
