# Generated by Django 4.2.3 on 2023-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0011_alter_joboffer_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='vacancy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
