# Generated by Django 4.2.3 on 2023-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0012_joboffer_vacancy_alter_joboffer_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='work_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='specialization',
            field=models.CharField(default='home office work', max_length=100),
        ),
    ]
