# Generated by Django 4.2.3 on 2023-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0013_joboffer_work_mode_alter_joboffer_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
