# Generated by Django 4.2.3 on 2023-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0016_joboffer_background_color_alter_joboffer_svg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_application_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
