# Generated by Django 4.2.3 on 2023-11-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0017_alter_joboffer_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
