# Generated by Django 4.2.3 on 2023-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0018_alter_joboffer_job_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_offer_status',
            field=models.BooleanField(default=False),
        ),
    ]
