# Generated by Django 4.2.3 on 2023-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0019_joboffer_job_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_about',
            field=models.TextField(default='test'),
        ),
    ]
