# Generated by Django 4.2.3 on 2023-11-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0021_alter_joboffer_job_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='job_responsibilities',
        ),
        migrations.CreateModel(
            name='JobOfferResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_responsibility', models.CharField(blank=True, max_length=300)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.joboffer')),
            ],
        ),
    ]
