# Generated by Django 4.2.3 on 2023-11-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0022_remove_joboffer_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobofferresponsibility',
            name='job_responsibility',
            field=models.CharField(max_length=300),
        ),
    ]
