# Generated by Django 4.2.3 on 2023-11-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0023_alter_jobofferresponsibility_job_responsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='job_requirements',
        ),
        migrations.CreateModel(
            name='JobOfferRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_requirement', models.CharField(max_length=300)),
                ('requirement_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional')], max_length=40)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.joboffer')),
            ],
        ),
    ]
