# Generated by Django 4.2.3 on 2023-11-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0028_remove_joboffer_application_process_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobofferapplication',
            old_name='job_application_process',
            new_name='job_application_stage',
        ),
    ]
