# Generated by Django 4.2.3 on 2023-11-20 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0030_alter_joboffer_job_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='background_color',
            field=models.CharField(blank=True, default='#f7f2f2', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code. (e.g. #RRGGBB or #RGB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='svg_color',
            field=models.CharField(blank=True, default='#2c2cdb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code. (e.g. #RRGGBB or #RGB)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
