# Generated by Django 4.2.3 on 2023-11-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0032_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.joboffer'),
        ),
    ]
