# Generated by Django 4.2.3 on 2023-11-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0033_jobapplication_status_alter_jobapplication_job_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company_app.joboffer'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='vacancy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='work_mode',
            field=models.CharField(max_length=100),
        ),
    ]
