# Generated by Django 4.2.3 on 2023-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0034_alter_jobapplication_job_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='job_description',
        ),
    ]
