# Generated by Django 4.2.3 on 2023-11-26 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0035_remove_joboffer_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
