# Generated by Django 4.2.3 on 2023-11-26 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0036_alter_joboffer_salary_max_alter_joboffer_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999.99)]),
        ),
    ]
