# Generated by Django 4.2.3 on 2023-12-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0038_alter_joboffer_salary_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300)),
                ('choices', models.JSONField(blank=True)),
                ('correct_choice', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='has_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobOfferExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='company_app.joboffer')),
                ('questions', models.ManyToManyField(related_name='exams', to='company_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_answers', to='company_app.jobapplication')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='exam_answers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_answers', to='company_app.jobapplicationexam'),
        ),
    ]
