# Generated by Django 4.2.3 on 2023-12-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0040_remove_question_choices_question_choice_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
