# Generated by Django 4.2.3 on 2023-12-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0041_rename_text_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='job_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_app.joboffer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobOfferExam',
        ),
    ]
