# Generated by Django 4.2.3 on 2023-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0042_question_job_offer_delete_jobofferexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
