# Generated by Django 4.2.3 on 2023-12-11 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0044_alter_question_choice_a_alter_question_choice_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='exam_pass_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Pass percentage required for the exam', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
