# Generated by Django 4.2.3 on 2023-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userlink_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='test',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
