# Generated by Django 4.2.3 on 2023-08-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_link',
        ),
    ]
