# Generated by Django 4.2.3 on 2023-08-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
