# Generated by Django 4.2.3 on 2023-10-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_user_about_me_user_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=10),
        ),
    ]
