# Generated by Django 4.2.3 on 2023-10-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_user_profile_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_background',
            new_name='background_image',
        ),
    ]
