# Generated by Django 4.2.3 on 2023-10-21 15:13

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_alter_user_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(default='defaults/default_background_image.png', null=True, upload_to=user_app.models.profile_background_image_upload_path),
        ),
    ]
