# Generated by Django 4.2.3 on 2023-07-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
