# Generated by Django 4.2.3 on 2023-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
