# Generated by Django 4.2.3 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userlink_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='test',
        ),
        migrations.AlterField(
            model_name='userlink',
            name='link_name',
            field=models.CharField(max_length=50),
        ),
    ]
