# Generated by Django 4.2.3 on 2023-07-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userworkeducation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWorkEducation',
            new_name='UserExpirience',
        ),
    ]
