# Generated by Django 4.2.3 on 2023-07-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_userworkeducation_userexpirience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExpirience',
            new_name='UserExperience',
        ),
    ]
