# Generated by Django 4.2.3 on 2023-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_userexpirience_userexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
