# Generated by Django 4.2.3 on 2023-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userexperience_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, default=models.EmailField(max_length=254, unique=True), max_length=254, null=True),
        ),
    ]
