# Generated by Django 4.2.3 on 2023-08-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
