# Generated by Django 4.2.3 on 2023-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
