# Generated by Django 4.2.3 on 2023-08-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userexperience_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
