# Generated by Django 4.2.3 on 2023-08-21 10:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='defaults/default_profile_image.jpg', null=True, upload_to=app.models.profile_image_upload_path),
        ),
    ]
