# Generated by Django 4.2.3 on 2023-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_usercourse_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
