# Generated by Django 4.2.3 on 2023-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_usercourse_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
